# Generated by Django 3.1 on 2022-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('servis', models.CharField(max_length=250, verbose_name='Услуги')),
                ('address', models.CharField(max_length=250, verbose_name='Адресс')),
                ('metro', models.CharField(max_length=250, verbose_name='Метро')),
                ('sale', models.IntegerField(verbose_name='Скидка')),
                ('placeType', models.CharField(max_length=250, verbose_name='Тип')),
            ],
        ),
    ]
