# Generated by Django 3.1 on 2022-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, upload_to='task/%Y/%m/%d/'),
        ),
    ]
