# Generated by Django 3.1 on 2022-01-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220116_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, upload_to='task/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
