# Generated by Django 3.1 on 2022-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220116_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='placeType',
            field=models.CharField(choices=[('KR', 'Кафе/ресторны'), ('M', 'Магазины'), ('R', 'Развлечения'), ('O', 'Одежда')], max_length=250, verbose_name='Тип'),
        ),
    ]
