# Generated by Django 3.1 on 2022-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220116_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='imageQR',
            field=models.ImageField(blank=True, upload_to='task/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
