# Generated by Django 3.1 on 2022-01-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tasks_imageqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='productLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
