# Generated by Django 3.1 on 2022-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tasks_productlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='promoCod',
            field=models.CharField(blank=True, max_length=250, verbose_name='Промокод'),
        ),
    ]
