# Generated by Django 3.1 on 2022-02-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220213_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='mapLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='imageQR',
            field=models.ImageField(blank=True, upload_to='task/%Y/%m/%d/', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='productLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на сайт'),
        ),
    ]
