# Generated by Django 3.1 on 2022-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220213_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='placeType',
            field=models.CharField(choices=[('KR', 'Кафе/ресторны'), ('M', 'Магазины'), ('R', 'Развлечения'), ('Z', 'Здоровье'), ('O', 'Остальное'), ('P', 'Путешествия'), ('ALL', 'Все')], max_length=250, verbose_name='Тип'),
        ),
    ]
