# Generated by Django 3.1 on 2022-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220214_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='ad',
            field=models.BooleanField(default=False, verbose_name='Реклама по категориям'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='placeType',
            field=models.CharField(choices=[('KR', 'Кафе/ресторны'), ('M', 'Магазины'), ('R', 'Развлечения'), ('Z', 'Здоровье'), ('O', 'Остальное'), ('P', 'Путешествия'), ('RECL', 'Реклама')], max_length=250, verbose_name='Тип'),
        ),
    ]
