# Generated by Django 3.1 on 2022-02-23 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220218_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dateFor',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Действрует до'),
        ),
    ]
