# Generated by Django 3.1 on 2022-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tasks_datefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dateFor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Действрует до'),
        ),
    ]
