# Generated by Django 3.1 on 2022-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220223_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='secondLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительная ссылка'),
        ),
    ]
