# Generated by Django 3.1 on 2022-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tasks_secondlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
    ]
