# Generated by Django 3.1 on 2022-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tasks_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='saleType',
            field=models.CharField(choices=[('Скидка', 'Скидка'), ('Кешбек', 'Кешбек')], default='Скидка', max_length=255, verbose_name='Вид скидки'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='sale',
            field=models.IntegerField(verbose_name='Размер скидки'),
        ),
    ]
