# Generated by Django 3.1 on 2022-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220313_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='secondLinkText',
            field=models.CharField(default='Открыть страницу с предложением', max_length=255, verbose_name='Текст дополнительной ссылки'),
        ),
    ]
